# Generated by Django 5.2.1 on 2025-05-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="test_cases",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
